execute:
  freeze: auto

project:
  type: website
  preview:
    port: 3438

website:
  description: "A blog built with Quarto"
  site-url: https://Ian-P-McCabe.github.io/blog # you must change this appropriately for RSS feeds to work properly
  title: "Ian's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Ian-P-McCabe
      - icon: linkedin
        href: https://www.linkedin.com/in/ianpmccabe/
  open-graph: true
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



